_target_: proteinworkshop.features.factory.ProteinFeaturiser
representation: CA
scalar_node_features:
  - amino_acid_one_hot
  - dihedrals
  - sidechain_torsions
  - alpha
  - kappa
vector_node_features: ["orientation"]
edge_types:
  - knn_16
scalar_edge_features:
  - edge_distance
  - edge_type
  - node_features
  - sequence_distance
vector_edge_features: ["edge_vectors"]
