name: protein
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.1.31=hbcca054_0
  - ipykernel=6.29.5=pyh3099207_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.15=h5eee18b_0
  - pip=25.0=py311h06a4308_0
  - python=3.11.11=he870216_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiobotocore==2.20.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - anndata==0.11.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - appdirs==1.4.4
      - array-api-compat==1.10.0
      - asttokens==3.0.0
      - attrs==25.1.0
      - beartype==0.15.0
      - beautifulsoup4==4.13.3
      - biopandas==0.5.1
      - biopython==1.85
      - bioservices==1.12.0
      - biothings-client==0.4.1
      - biotite==0.37.0
      - bleach==6.2.0
      - blessed==1.20.0
      - bokeh==3.6.3
      - botocore==1.36.23
      - captum==0.6.0
      - cattrs==24.1.2
      - cellxgene-census==1.16.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - colorcet==3.1.0
      - colorlog==6.9.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cpdb-protein==0.2.0
      - cycler==0.12.1
      - cython==3.0.12
      - dask==2025.2.0
      - dataclasses==0.6
      - datashader==0.16.3
      - debugpy==1.8.12
      - decorator==5.2.1
      - deepdiff==8.2.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - e3nn==0.5.5
      - easydev==0.13.3
      - einops==0.6.1
      - et-xmlfile==2.0.0
      - executing==2.2.0
      - fair-esm==2.0.0
      - fastcore==1.7.29
      - filelock==3.17.0
      - foldcomp==0.0.5
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - fuzzywuzzy==0.18.0
      - gevent==24.11.1
      - gget==0.29.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gpustat==1.1.1
      - graphein==1.7.7
      - greenlet==3.1.1
      - grequests==0.7.0
      - h11==0.14.0
      - h5py==3.13.0
      - holoviews==1.20.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.1
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipython==8.32.0
      - ipywidgets==8.1.5
      - jaxtyping==0.2.38
      - jedi==0.19.2
      - jinja2==3.1.5
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonargparse==4.37.0
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - legacy-api-wrap==1.4.1
      - lightning==2.5.0.post0
      - lightning-utilities==0.12.0
      - line-profiler==4.2.0
      - linkify-it-py==2.0.3
      - llvmlite==0.44.0
      - locket==1.0.0
      - loguru==0.7.3
      - looseversion==1.1.2
      - lovely-numpy==0.2.13
      - lovely-tensors==0.1.18
      - lxml==5.3.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mmtf-python==1.1.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - mygene==3.2.2
      - mysql-connector-python==9.2.0
      - narwhals==1.27.1
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - orderly-set==5.3.0
      - packaging==24.2
      - pandas==2.1.4
      - panel==1.6.1
      - param==2.2.0
      - parso==0.8.4
      - partd==1.4.2
      - pathtools==0.1.2
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - plotly==6.0.0
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - proteinvirtual==0.1.0
      - proteinworkshop==0.2.5
      - protobuf==4.25.6
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pyarrow-hotfix==0.6
      - pyct==0.5.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydeprecate==0.3.2
      - pygments==2.19.1
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyrootutils==1.0.4
      - pytdc==0.4.17
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==1.9.5
      - pytz==2025.1
      - pyviz-comms==3.0.4
      - pyyaml==6.0.2
      - rdkit==2023.9.6
      - requests==2.32.3
      - requests-cache==1.2.1
      - rich==13.9.4
      - rich-click==1.8.6
      - s3fs==2025.2.0
      - scanpy==1.11.0
      - scikit-learn==1.5.2
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - session-info2==0.1.2
      - setproctitle==1.3.5
      - shapely==2.0.7
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - somacore==1.0.26
      - soupsieve==2.6
      - speedtest-cli==2.1.3
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - suds-community==1.2.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tiledbsoma==1.15.7
      - toolz==1.0.0
      - torch==2.1.2+cu118
      - torch-cluster==1.6.3+pt21cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt21cu118
      - torch-sparse==0.6.18+pt21cu118
      - torch-spline-conv==1.2.2+pt21cu118
      - torchaudio==2.1.2+cu118
      - torchmetrics==1.3.1
      - torchvision==0.16.2+cu118
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==2.1.0
      - typeshed-client==2.7.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uc-micro-py==1.0.3
      - umap-learn==0.5.7
      - url-normalize==1.4.3
      - urllib3==2.3.0
      - wadler-lindig==0.1.3
      - wandb==0.15.12
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - wget==3.2
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xarray==2025.1.2
      - xmltodict==0.14.2
      - xyzservices==2025.1.0
      - yapf==0.43.0
      - yarl==1.18.3
      - zipp==3.21.0
      - zope-event==5.0
      - zope-interface==7.2
prefix: /home/linus/.miniconda3/envs/protein
